hyperskill_project:
  id: 53
  ide_files: https://cogniterra.org/media/attachments/lesson/23036/additional_files.json
  is_template_based: false
  use_ide: true
update_date: "Thu, 01 Jan 1970 00:00:00 UTC"
stages:
  - id: 287
    step: 5429
    is_completed: true
  - id: 288
    step: 5430
    is_completed: true
  - id: 289
    step: 5431
    is_completed: true
  - id: 290
    step: 5432
    is_completed: true
  - id: 291
    step: 5433
    is_completed: true
  - id: 292
    step: 5434
    is_completed: true
  - id: 293
    step: 5435
    is_completed: true
topics:
  0:
    - title: Introduction to Java
      theory_id: 38627
    - title: "Basic literals: numbers, strings and characters"
      theory_id: 3522
    - title: Writing first program
      theory_id: 3521
    - title: Printing data
      theory_id: 3749
    - title: Types and variables
      theory_id: 3518
    - title: Comments
      theory_id: 3520
    - title: Reading user's input with Scanner
      theory_id: 9055
    - title: Coding style conventions
      theory_id: 12411
    - title: Naming variables
      theory_id: 3513
    - title: Arithmetic operations
      theory_id: 3519
    - title: Integer types and operations
      theory_id: 3565
    - title: Increment and decrement
      theory_id: 5008
    - title: Data types and their sizes
      theory_id: 3532
    - title: Type casting
      theory_id: 3510
    - title: Characters
      theory_id: 3514
  1:
    - title: Calling methods
      theory_id: 10973
    - title: Floating-point types
      theory_id: 3517
    - title: Boolean type and operations. True and false
      theory_id: 3516
    - title: Comparing values. Relational operators
      theory_id: 3512
    - title: Conditional statement
      theory_id: 3503
    - title: One-line condition with ternary operator
      theory_id: 3506
    - title: While and do-while loops
      theory_id: 3498
    - title: For-loop
      theory_id: 3505
    - title: Break and continue. Branching
      theory_id: 3507
    - title: Primitive and reference types
      theory_id: 5035
    - title: Array
      theory_id: 3511
    - title: String
      theory_id: 3523
    - title: Processing strings
      theory_id: 3551
  2:
    - title: "Write, compile, and run"
      theory_id: 3739
    - title: Declaring methods
      theory_id: 10982
    - title: Method "main"
      theory_id: 3489
    - title: "Multiple conditions: switch"
      theory_id: 3504
    - title: Functional decomposition
      theory_id: 10570
    - title: StringBuilder
      theory_id: 3812
    - title: Defining classes
      theory_id: 3618
    - title: Objects and their properties
      theory_id: 4727
  3:
    - title: IntelliJ IDEA
      theory_id: 37202
  5:
    - title: Arrays as parameters
      theory_id: 3594
    - title: Grouping classes with packages
      theory_id: 3621
    - title: Instance methods
      theory_id: 3495
    - title: Initializing new instances. Constructor
      theory_id: 3535
    - title: Access modifiers
      theory_id: 3589
  6:
    - title: Overloading
      theory_id: 3525
    - title: Errors in programs
      theory_id: 3536
    - title: First glance at exceptions
      theory_id: 3497
    - title: Hierarchy of exceptions
      theory_id: 3570
    - title: Exception handling
      theory_id: 3552
    - title: Getters and setters
      theory_id: 3599
    - title: Inheritance
      theory_id: 3583
    - title: Multiple constructors
      theory_id: 3538
    - title: Keyword "super"
      theory_id: 3588
